@echo off

REM Remove temporary files generated by MPLAB X

echo Removing "*.X\build" directory...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.X"') do rd "%%i\build" /s /q
echo.

echo Removing "*.X\disassembly" directory...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.X"') do rd "%%i\disassembly" /s /q
echo.

REM echo Removing "*.X\dist" directory...
REM for /f "delims==" %%i in ('dir /b /on /s "%~p0*.X"') do rd "%%i\dist" /s /q
REM echo.

echo Removing "*.cof" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.cof"') do del "%%i" /f /q
echo.

echo Removing "*.elf" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.elf"') do del "%%i" /f /q
echo.

echo Removing "*.map" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.map"') do del "%%i" /f /q
echo.

echo "%~n0.bat" done.
