@echo off

REM Remove temporary files generated by MPLAB X

echo Removing "MPLAB.X\build" directory...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*MPLAB.X"') do rd "%%i\build" /s /q
echo.

echo Removing "MPLAB.X\debug" directory...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*MPLAB.X"') do rd "%%i\debug" /s /q
echo.

echo Removing "MPLAB.X\disassembly" directory...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*MPLAB.X"') do rd "%%i\dist" /s /q
echo.

echo Removing "MPLAB.X\dist" directory...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*MPLAB.X"') do rd "%%i\disassembly" /s /q
echo.

echo Removing "MPLAB.X\nbproject\private" directory...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*MPLAB.X"') do rd "%%i\nbproject\private" /s /q
echo.

echo Removing "MPLAB.X\nbproject\*.mk" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0\MPLAB.X\nbproject\*.mk"') do del "%%i" /f /q
echo.

echo Removing "MPLAB.X\nbproject\*.bash" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0\MPLAB.X\nbproject\*.bash"') do del "%%i" /f /q
echo.

echo Removing "MPLAB.X\nbproject\*.properties" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0\MPLAB.X\nbproject\*.properties"') do del "%%i" /f /q
echo.

echo Removing "MPLAB.X\nbproject\.dep.inc" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0\MPLAB.X\nbproject\.dep.inc"') do del "%%i" /f /q
echo.

echo "%~n0.bat" done.
